version: '3.8'
services:
  web:
    build: .
    command: python run.py
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
      image: postgres
      restart: always
      ports:
        - '5436:5432'
      environment:
        POSTGRES_DB: postgres
        POSTGRES_PASSWORD: postgres
